audit_header: false
title: "Triad's Best Real Estate Training"
description: Jason Bramblett, a top Real Estate Agent in Triad, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: #
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/


client:
  name: Jason Bramblett
  title:
  license_number:
  about_markdown: |
    Jason Bramblett Real Estate marketing system is on a whole different level than the average agent or brokerage. The average agent needs an entire year to sell 5 homes. Jason’s team averages selling a home every 48 hours! The Marketing system they have reaches thousands of potential buyers each month. What does that mean to you? It means they have thousands of buyers creating demand for your home to get you the most money possible!
  market: Triad
  brand: Jason Bramblett Real Estate
  brokerage:
  address: 7031 Albert Pick Rd. Suite 104<br>Greensboro, NC 27409
  phone: 336-553-0796
  phone_type:
  phone2:
  phone2_type:
  email: jason@jasonbramblett.com
  url: http://www.jasonbramblett.com

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/JasonBramblettRealEstate
  linkedin_url: https://www.linkedin.com/company/1160873?trk=prof-exp-company-name
  youtube_url: https://www.youtube.com/channel/UCCrDcr0aFSJVVoOgeBPOC9A/featured
  twitter_url: https://twitter.com/jasonbramblett
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Triad Real Estate Podcast with Jason Bramblett'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Triad Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Jason Bramblett Real Estate - your professional Triad Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Triad, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Jason Bramblett'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Triad Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#1d4670'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
